In [1]:
#pandas的数据结构 series dataframe 以及基础功能
# panda是基于numpy开发   注意首字母大写
from pandas import Series,DataFrame
import pandas as pd

In [4]:
#1 Series 一种类似于一维数组的对象 由一组numpy数据和与之相应的索引组成
#1.1.1  series对象通过数组创建   values 属性值是numpy数组    index属性值  ---> 自动创建     2种属性
# series对象本身以及索引都有一个name属性
obj1 = Series([1,2,3,4])
obj1

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
obj1.values

array([1, 2, 3, 4])

In [6]:
obj1.index

RangeIndex(start=0, stop=4, step=1)

In [33]:
obj1.name = 'name_attribuate'
obj1

0    1
1    2
2    3
3    4
Name: name_attribuate, dtype: int64

In [35]:
obj1.index.name = 'name_inde_attribuate'
obj1

name_inde_attribuate
0    1
1    2
2    3
3    4
Name: name_attribuate, dtype: int64

In [7]:
obj2 = Series([[1,2,3,4],[4,5,6,7]])
obj2

0    [1, 2, 3, 4]
1    [4, 5, 6, 7]
dtype: object

In [8]:
obj2.values

array([[1, 2, 3, 4], [4, 5, 6, 7]], dtype=object)

In [9]:
obj2.index

RangeIndex(start=0, stop=2, step=1)

In [10]:
#1.1.2 手动创建标记索引
obj3 = Series([1,2,3,4],index=['d','e','f','g'])
obj3

d    1
e    2
f    3
g    4
dtype: int64

In [11]:
obj3.index

Index(['d', 'e', 'f', 'g'], dtype='object')

In [12]:
obj3['d']

1

In [13]:
#1.2 数组之间运算不影响索引与值的链接
obj3

d    1
e    2
f    3
g    4
dtype: int64

In [14]:
obj2

0    [1, 2, 3, 4]
1    [4, 5, 6, 7]
dtype: object

In [15]:
obj3*3

d     3
e     6
f     9
g    12
dtype: int64

In [19]:
obj3[obj3>2]

f    3
g    4
dtype: int64

In [20]:
#1.3 通过字典创建Series对象  只传入字典    series对象索引默认使用字典的键
data = {'wang':1,'meng':2,'wei':3}
data_series = Series(data)

In [21]:
data_series

meng    2
wang    1
wei     3
dtype: int64

In [22]:
data_series.values

array([2, 1, 3])

In [23]:
data_series.index

Index(['meng', 'wang', 'wei'], dtype='object')

In [28]:
#1.3.2 通过字典创建Series对象  传入字典和标记索引 则使用标记索引 
data_series2 = Series(data,index=['wang','wei','lio'])

In [29]:
#标记索引与字典的键值进行匹配然后显示
data_series2

wang    1.0
wei     3.0
lio     NaN
dtype: float64

In [30]:
data_series2.index

Index(['wang', 'wei', 'lio'], dtype='object')

In [31]:
#1.4 Series  在算术运算中会自动对齐不同索引的数据

In [32]:
obj5 = Series([1,2,3,4],index = ['A','B','C','D'])
obj6 = Series([7,8,9,1],index =['a','B','C','d'])
obj5+obj6

A     NaN
B    10.0
C    12.0
D     NaN
a     NaN
d     NaN
dtype: float64

In [36]:
#2. dataframe 1.一个表格型数据结构  2.含有一组有序的列 每列都是不同的值类型(数值 字符串 布尔值等)
#            3.含有行索引和列索引  4.看做Series组成的字典

In [ ]:
#2.1.1 传入等长的列表或者numpy数组对象组成的字典    
#         自动创建行索引标记  键值作为列索引 列表元素有序排列
data1 = {'name':['wang','wei','neng','neng'],
         'year':[2010,2011,2010,2011],
         'pop':[1.2,1.2,2.1,3.1],
        }
frame1 = DataFrame(data1)
frame1

In [41]:
#  可以指定列索引顺序 添加参数columns
frame2 = DataFrame(data1,columns = ['year','pop','name'])
frame2


year  pop  name
0  2010  1.2  wang
1  2011  1.2   wei
2  2010  2.1  neng
3  2011  3.1  neng

In [43]:
# 可以定义行索引记号 与series对象相同 index
frame3 = DataFrame(data1,columns = ['year','name','pop'],index = ['one','two','three','four'])
frame3

year  name  pop
one    2010  wang  1.2
two    2011   wei  1.2
three  2010  neng  2.1
four   2011  neng  3.1

In [44]:
#2.1.2 获取某一行，某一列   对某一列赋值    添加某一列    删除某一列 


In [45]:
#获取某一列 为series对像  2种方法
frame3['year']

one      2010
two      2011
three    2010
four     2011
Name: year, dtype: int64

In [46]:
frame3.year

one      2010
two      2011
three    2010
four     2011
Name: year, dtype: int64

In [47]:
#获取某一行  dataframe.ix['索引']
frame3.ix['two']

year    2011
name     wei
pop      1.2
Name: two, dtype: object

In [49]:
# 创建一个列gg  1.在columans参数上添加 
frame4 = DataFrame(data1,columns = ['year','name','pop','gg'],index =  ['one','two','three','four'])
frame4

year  name  pop   gg
one    2010  wang  1.2  NaN
two    2011   wei  1.2  NaN
three  2010  neng  2.1  NaN
four   2011  neng  3.1  NaN

In [54]:
#创建一个新的布尔列hh  
frame4['hh'] = frame4.year == 2010
frame4

year  name  pop   gg     hh
one    2010  wang  1.2  5.0   True
two    2011   wei  1.2  3.0  False
three  2010  neng  2.1  4.0   True
four   2011  neng  3.1  NaN  False

In [56]:
# 删除一列
del frame4['hh']
frame4

year  name  pop   gg
one    2010  wang  1.2  5.0
two    2011   wei  1.2  3.0
three  2010  neng  2.1  4.0
four   2011  neng  3.1  NaN

In [50]:
# 在新列上赋值 1.标量
frame4['gg'] = 9
frame4

year  name  pop  gg
one    2010  wang  1.2   9
two    2011   wei  1.2   9
three  2010  neng  2.1   9
four   2011  neng  3.1   9

In [51]:
#           2.赋值列表或数组 长度和DataFrame长度一致
frame4['gg'] = range(4)
frame4

year  name  pop  gg
one    2010  wang  1.2   0
two    2011   wei  1.2   1
three  2010  neng  2.1   2
four   2011  neng  3.1   3

In [53]:
#           3.赋值series对象 则会精确匹配dataframe的索引 没有匹配的定义为缺失值
frame4['gg'] = Series([4,5,3],index = ['three','one','two'])
frame4

year  name  pop   gg
one    2010  wang  1.2  5.0
two    2011   wei  1.2  3.0
three  2010  neng  2.1  4.0
four   2011  neng  3.1  NaN

In [57]:
#2.2 另一种形式frame 字典的字典  外层字典的键作为列 内层字典的键作为行索引

In [58]:
data2 = {'wang':{'year':1993,'age':24},
          'wei':{'year':1994,'age':23,'gender':'woman'},
        }
frame5 = DataFrame(data2)
frame5

wang    wei
age       24.0     23
gender     NaN  woman
year    1993.0   1994

In [60]:
frame5.T

age gender  year
wang  24    NaN  1993
wei   23  woman  1994

In [61]:
#  设置行索引以及列索引的name属性
frame5.index.name = 'index_attribuate'
frame5.columns.name = 'columns_attribuate'
frame5

columns_attribuate    wang    wei
index_attribuate                 
age                   24.0     23
gender                 NaN  woman
year                1993.0   1994

In [62]:
# frame的name属性
frame5.name = 'frame_name'
frame5

columns_attribuate    wang    wei
index_attribuate                 
age                   24.0     23
gender                 NaN  woman
year                1993.0   1994

In [63]:
frame6 = DataFrame([[1,2,3,4],[2,3,4,5]])
frame6

0  1  2  3
0  1  2  3  4
1  2  3  4  5

In [64]:
frame7 = DataFrame(frame5)
frame7

columns_attribuate    wang    wei
index_attribuate                 
age                   24.0     23
gender                 NaN  woman
year                1993.0   1994

#总结：
可以输入DataFrame构造器的数据
1. 传入等长的列表或者numpy数组对象组成的字典
2.由字典组成的字典SS
3.由 series组成的字典
4.二维的ndarry
5.另一个DataFrame




In [1]:
# index 对象
#pandas 的索引对象负责管理轴标签和其他元数据（比如轴名称等） 
#   构建series dataframe 使用的数组或者序列标签都会转换成为一个index对象
#   索引对象不可修改

In [5]:
import pandas as pd
from pandas import Series,DataFrame
obj = Series(range(3),index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [6]:
#索引对象不可更改
index[1] = 'f'

TypeError: Index does not support mutable operations

In [ ]:
# 索引对象Index 的属性以及方法
#   append  连接另一个Index对象产生一个新的Index
#   insert delete  插入（删除）索引i处的元素 
#    drop  删除传入的值 并得到新的index
#     unique 计算index中唯一值的数组